### ISSUE TITLE
Restforce deletes external id from attrs hash in update and upsert method

### ISSUE THREAD

**Issue by synth** [ejholmes/restforce#159] opened 2014-12-16 20:17 UTC
See: https://github.com/ejholmes/restforce/blob/master/lib/restforce/concerns/api.rb#L263

````ruby
  def upsert!(sobject, field, attrs)
    external_id = attrs.delete(attrs.keys.find { |k| k.to_s.downcase == field.to_s.downcase })
    response = api_patch "sobjects/#{sobject}/#{field.to_s}/#{external_id}", attrs
    (response.body && response.body['id']) ? response.body['id'] : true
  end
````
In the call to update and upsert the external id is deleted from the attributes hash. This will delete it from upstream clients data structures as well because its all passed by reference.  This was unexpected behavior and I had to dig through Restforce source to figure out why a data structure I passed to Restforce came back modified(ie missing the external id key/value)

Perhaps, restforce should dupe the structure first before modifying it.  Is there perhaps another reason to delete it directly?

**Comment by timrogers** [comment] 2015-06-26 16:19
Fixed in https://github.com/ejholmes/restforce/pull/185 - this will get merged in the next day or two.

**Closed** 2015-06-26 16:19 UTC

**Comment by velveret** [comment] 2017-04-11 20:52
We're seeing this issue again because of the switch back to `hash.delete`: https://github.com/ejholmes/restforce/blob/v2.5.1/lib/restforce/concerns/api.rb#L492

**Comment by timrogers** [comment] 2017-04-11 21:06
@velveret Good spot - this wasn't intended. Can you implement a fix and a regression test? (I'm happy to but always good to have new contributors!)
